name: Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
  schedule:
    - cron: "0 8 * * 1"
  workflow_dispatch:

permissions: {}

concurrency:
  group: security-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scan:
    permissions:
      contents: read
      security-events: write
      actions: read
    uses: NWarila/terraform-template/.github/workflows/reusable-iac-security.yaml@2f343e5c4bc7f069f27628dfe0b597eb96f34b05
