name: Template Sync

on:
  schedule:
    - cron: "17 6 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: template-sync
  cancel-in-progress: false

jobs:
  sync:
    uses: NWarila/terraform-template/.github/workflows/reusable-template-sync.yaml@3ace29557816e44a7680d69856e2c9d6a4c1cee5
    with:
      template_ref: 3ace29557816e44a7680d69856e2c9d6a4c1cee5
